### PR TITLE
Feature/phy detect

### LINKED ISSUE #242: Document different PHY implications, build firmware
Basically what the title says. After flashing, the device will reset to "run" mode, the fans come on for a few seconds at full power, then slow down, and after a few seconds the interlock LEDs briefly turn on before the cycle starts again.

Hardware: Booster v1.6
dfu-util version: tried with both v0.9 and v0.11
Firmware version: tried with prebuilt binaries for v0.4.0, v0.3.0, and v0.2.0, also tried with local build from current head of `develop` branch as well as from #237 

Output of `dfu-util -l`:
```
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Cannot open DFU device 19ff:0239 found on devnum 3 (LIBUSB_ERROR_ACCESS)
Found DFU: [0483:df11] ver=2200, devnum=87, cfg=1, intf=0, path="3-6.1", alt=3, name="@Device Feature/0xFFFF0000/01*004 e", serial="2064328C5242"
Found DFU: [0483:df11] ver=2200, devnum=87, cfg=1, intf=0, path="3-6.1", alt=2, name="@OTP Memory /0x1FFF7800/01*512 e,01*016 e", serial="2064328C5242"
Found DFU: [0483:df11] ver=2200, devnum=87, cfg=1, intf=0, path="3-6.1", alt=1, name="@Option Bytes  /0x1FFFC000/01*016 e", serial="2064328C5242"
Found DFU: [0483:df11] ver=2200, devnum=87, cfg=1, intf=0, path="3-6.1", alt=0, name="@Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg", serial="2064328C5242"
```

Output of `dfu-util -a 0 -s 0x08000000:leave -v --download ~/Downloads/booster-release.bin` (in this case prebuilt binary for v0.4.0):
```
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

libusb version 1.0.26 (11724)
dfu-util: Warning: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release
dfu-util: Cannot open DFU device 19ff:0239 found on devnum 3 (LIBUSB_ERROR_ACCESS)
Opening DFU capable USB device...
Device ID 0483:df11
Device DFU version 011a
DFU attributes: (0x0b) bitCanDnload bitCanUpload bitWillDetach
Detach timeout 255 ms
Claiming USB DFU Interface...
Setting Alternate Interface #0 ...
Determining device status...
DFU state(10) = dfuERROR, status(10) = Device's firmware is corrupt. It cannot return to run-time (non-DFU) operations
Clearing status
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Memory segment at 0x08000000   4 x 16384 = 65536 (rew)
Memory segment at 0x08010000   1 x 65536 = 65536 (rew)
Memory segment at 0x08020000   7 x 131072 = 917504 (rew)
Downloading element to address = 0x08000000, size = 379312
Erasing page size 16384 at address 0x08000000, page starting at 0x08000000
Erasing page size 16384 at address 0x08004000, page starting at 0x08004000
Erasing page size 16384 at address 0x08008000, page starting at 0x08008000
Erasing page size 16384 at address 0x0800c000, page starting at 0x0800c000
Erasing page size 65536 at address 0x08010000, page starting at 0x08010000
Erasing page size 131072 at address 0x08020000, page starting at 0x08020000
Erasing page size 131072 at address 0x08040000, page starting at 0x08040000
 Download from image offset 00000000 to memory 08000000-080007ff, size 2048
 Download from image offset 00000800 to memory 08000800-08000fff, size 2048
 Download from image offset 00001000 to memory 08001000-080017ff, size 2048

...(redacted for readability)

 Download from image offset 0005b800 to memory 0805b800-0805bfff, size 2048
 Download from image offset 0005c000 to memory 0805c000-0805c7ff, size 2048
 Download from image offset 0005c800 to memory 0805c800-0805c9af, size 432
File downloaded successfully
Submitting leave request...
Transitioning to dfuMANIFEST state
```

### LINKED ISSUE #243: Investigate unifying PHY support
Investigate the possibility of run-time PHY detection and selection. This would ease issues encountered in https://github.com/quartiq/booster/issues/242

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR fixes #243 by adding runtime detection of the PHY.

This PR closes #242 as unnecessary, as there will now be a single firmware build

I haven't been able to test with the ENC424J600 because I do not have the hardware, but the detection works as expected for the W5500 - theoretical analysis indicates that this should properly work with the ENC424J600, but we should verify.

@occheung Do you have the ability to test out this PR?

### CODE REVIEW

**Comment by occheung** [comment]
> @occheung Do you have the ability to test out this PR?

No. I do not have the hardware.

**Comment by ryan-summers** [comment]
@b-bondurant If you're feeling adventurous, would love to have someone test this out for me. I do not have any contacts who have the ENC424J600 readily available otherwise.

@sbourdeauducq Are you aware of anyone that could test this at M-labs?

**Comment by thomasfire** [comment]
Yes, please provide detailed testing steps and the desired behavior.

**Comment by jordens** [comment]
@thomasfire just flash it and check whether DHCP and mqtt work. Since there are so few enc users out there and since we don't have the hardware for it nor the funding we can't maintain that code.

**Comment by thomasfire** [comment]
DHCP seems to work OK.

I did in serial:
```
write ip-address 0.0.0.0
write netmask 0.0.0.0
reset
```
Then in mqtt logs I see it connected from new IP address:
```
New client connected from 192.168.1.205:52903 as booster-80-34-28-1b-29-1f-settings (p5, c1, k60).
```

**Comment by ryan-summers** [comment]
Given that this appears to be working as I'd expect for the ENC424J600, this should be good to go. I've added the detected PHY to the service info for booster:
image

**Review by jordens — APPROVED** [review]

**Pull request merged**
