### PR TITLE
Adding Booster HITL support

### LINKED ISSUE #162: Add hardware-in-the-loop testing CI
Add HITL testing to Booster, similar to Stabilizer's HITL, so that we can automatically verify basic functionality of Booster on pull requests.

Basic operations:
* Program device
* Ping booster IP address
* Configure booster settings
* Monitor booster telemetry
* Set/Reset interlocks
* Tune bias current

### LINKED ISSUE #297: Add v1.6 hardware identification
Booster v1.6 uses hardware ID 0b101. Add it to the `HardwareVersion` enum

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR fixes https://github.com/quartiq/booster/issues/272 by locking MQTT to a tag
This PR fixes #162 by adding booster HITL support for booster
This PR fixes #297 by adding v1.6 identification support

### CODE REVIEW

**Comment by ryan-summers** [comment]
bors try

**Comment by jordens** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try-

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by jordens** [comment]
you'll also want to include the hitl run in the bors requirements for success

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
bors try

**Comment by ryan-summers** [comment]
@jordens I've made a lot of changes since your last review. Mind re-checking things here before we merge? HITL is broken because we do not yet support v1.6 hardware, but that's not the fault of the HITL infrastructure that we're landing here.

**Review by jordens — APPROVED** [review]

**Pull request merged**
